{{ config(materialized='table')}}

SELECT 
    GEOLOCATION_CITY as CITY,
    GEOLOCATION_LAT as LAT,
    GEOLOCATION_LNG as LNG,
    GEOLOCATION_STATE as STATE,
    GEOLOCATION_ZIP_CODE_PREFIX as ZIP_CODE
FROM RETAIL_DWH.RAW.GEOLOCATION